const actionTypes = {
  CHANGE_TODO: "CHANGE_TODO",
  EDIT_TODO: "EDIT_TODO",
  DELETE_TODO: "DELETE_TODO",
  LOAD_TODOS: "LOAD_TODOS",
  SEARCH_TODO: "SEARCH_TODO",
  CHANGE_TODO_NAME: "CHANGE_TODO_NAME",
  ADD_TODO: "ADD_TODO",
  SORT_TODO: 'SORT_TODO'
}
export default actionTypes
